export const SCHEMA = {
    testingSchema: 'hostiggo_testing_schema',
    tables: {
        listings: {
            tableName: "listings",
            columns: {
                listingId: "listing_id",
                title: "title",
                description: "description",
                priceWeekday: "price_weekday",
                priceWeekend: "price_weekend",
                numGuests: "num_guests",
                numBedrooms: "num_bedrooms",
                numBeds: "num_beds",
                numBathrooms: "num_bathrooms",
                isActive: "is_active",
                createdAt: "created_at",
                updatedAt: "updated_at",
                hostUuid: "host_uuid",
                checkInTime: "check_in_time",
                checkOutTime: "check_out_time",
                addressLine1: "address_line1",
                addressLine2: "address_line2",
                landmark: "landmark",
                longitude: "longitude",
                latitude: "latitude",
                locationId: "location_id",
                bookingMode: "booking_mode",
                currency: "currency",
                listingStatus: "lisiting_status",
                propertyTypeId: "property_type_id",
                stayTypeId: "stay_type_id",
                pincode: "pincode",
            },
        },
        listingDiscounts: {
            tableName: "listing_discounts",
            columns: {
                id: "id",
                listingId: "listing_id",
                discountType: "discount_type",
                percent: "percent",
                enabled: "enabled",
            },
        },
        listingHouseRules: {
            tableName: "listing_house_rules",
            columns: {
                listingId: "listing_id",
                checkInTime: "check_in_time",
                checkOutTime: "check_out_time",
                smokingAllowed: "smoking_allowed",
                petsAllowed: "pets_allowed",
                partiesAllowed: "parties_allowed",
                quietHours: "quiet_hours",
            },
        },
        listingBedrooms: {
            tableName: "listing_bedrooms",
            columns: {
                id: "id",
                listingId: "listing_id",
                bedroomIndex: "bedroom_index",
                beds: "beds",
                bathrooms: "bathrooms",
                maxGuests: "max_guests",
            },
        },
        listingAmenities: {
            tableName: "listing_amenities",
            columns: {
                listingId: "listing_id",
                amenityId: "amenity_id",
            },
        },
        amenities: {
            tableName: "amenities",
            columns: {
                amenityId: "amenity_id",
                name: "name",
                icon: "icon",
                category: "category",
            },
        },
        feedback: {
            tableName: "feedback",
            columns: {
                id: "id",
                userId: "user_id",
                type: "type",
                category: "category",
                description: "description",
                rating: "rating",
                comment: "comment",
                createdAt: "created_at",
            },
        },
        review: {
            tableName: "review",
            columns: {
                id: "review_id",
                listingId: "listing_id",
                rating: "rating",
                comment: "comment",
                reviewedAt: "reviewd_at",
                userId: "user_id",
            }
        },
        propertyTypes: {
            tableName: "property_types",
            columns: {
                id: "id",
                typeId: "type_id",
                name: "name",
                description: "description",
                icon: "icon",
                category: "category",
            },
        },
        addons: {
            tableName: 'addons',
            columns: {
                addonId: 'addon_id',
                name: 'name',
                icon: 'icon',
                category: 'category',
                createdAt: 'created_at',
            },
        },
        listingAddons: {
            tableName: 'listing_addons',
            columns: {
                id: 'id',
                listingId: 'listing_id',
                addonId: 'addon_id',
                price: 'price',
                includes: 'includes',
                timingFrom: 'timing_from',
                timingTo: 'timing_to',
                anotherDetails: 'another_details',
                additionalNotes: 'additional_notes',
                createdAt: 'created_at',
            },
        },
        stayTypes: {
            tableName: 'stay_types',
            columns: {
                id: 'id',
                typeId: 'type_id',
                title: 'title',
                description: 'description',
                logoUrl: 'logo_url',
            },
        },
        listingCalendar: {
            tableName: 'listing_calendar',
            columns: {
                calendarId: 'calendar_id',
                listingId: 'listing_id',
                date: 'date',
                price: 'price',
                currency: 'currency',
                isAvailable: 'is_available',
                createdAt: 'created_at',
                updatedAt: 'updated_at',
            },
        },
        bookings: {
            tableName: 'bookings',
            columns: {
                bookingId: 'booking_id',
                startDate: 'start_date',
                endDate: 'end_date',
                nomGuests: 'nom_guests',
                amount: 'amount',
                statusId: 'status_id',
                bookedAt: 'booked_at',
                listingId: 'listing_id',
                userId: 'user_id',
                numAdults: 'num_adults',
                numChildren: 'num_children',
                hostUuid: 'host_uuid',
                cancellationReason: 'cancellation_reason',
            },
        },
        listingMedia: {
            tableName: "listing_media",
            columns: {
                id: "id",
                listingId: "listing_id",
                mediaUrl: "media_url",
                mediaType: "media_type",
                isCover: "is_cover",
                uploadedAt: "uploaded_at",
            }
        },
        users: {
            tableName: "users",
            columns: {
                userId: "user_id",
                name: "name",
                email: "email",
                phone: "phone",
                age: "age",
                isActive: "is_active",
                isVerified: "is_verified",
                profilePicUrl: "profile_pic_url",
                emergencyContact: "emergency_contact",
                createdAt: "created_at",
                updatedAt: "updated_at",
            }
        },
    },
} as const;
